version: "3"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresDB:
